### ISSUE TITLE
Error occuried while loading SLIMJAR

### ISSUE THREAD

**Issue by editon96** [Picono435/PicoJobs#123] opened 2021-11-05 13:16 UTC
So after the configuration an Error happend:
[13:56:22 ERROR]: [PicoJobs] An error occuried while loading SLIMJAR, please contact a plugin developer with the following error:
[13:56:22 WARN]: UnresolvedDependencyException{dependency=com.google.code.gson:gson:2.8.6}
[13:56:22 WARN]:        at PicoJobs-1.0-beta-3d.jar//com.gmail.picono435.picojobs.libs.slimjar.downloader.URLDependencyDownloader.lambda$download$0(URLDependencyDownloader.java:76)
[13:56:22 WARN]:        at java.base/java.util.Optional.orElseThrow(Unknown Source)
[13:56:22 WARN]:        at PicoJobs-1.0-beta-3d.jar//com.gmail.picono435.picojobs.libs.slimjar.downloader.URLDependencyDownloader.download(URLDependencyDownloader.java:76)
[13:56:22 WARN]:        at PicoJobs-1.0-beta-3d.jar//com.gmail.picono435.picojobs.libs.slimjar.injector.helper.InjectionHelper.fetch(InjectionHelper.java:45)
[13:56:22 WARN]:        at PicoJobs-1.0-beta-3d.jar//com.gmail.picono435.picojobs.libs.slimjar.injector.SimpleDependencyInjector.injectDependencies(SimpleDependencyInjector.java:58)
[13:56:22 WARN]:        at PicoJobs-1.0-beta-3d.jar//com.gmail.picono435.picojobs.libs.slimjar.injector.SimpleDependencyInjector.inject(SimpleDependencyInjector.java:52)
[13:56:22 WARN]:        at PicoJobs-1.0-beta-3d.jar//com.gmail.picono435.picojobs.libs.slimjar.app.builder.InjectingApplicationBuilder.buildApplication(InjectingApplicationBuilder.java:63)
[13:56:22 WARN]:        at PicoJobs-1.0-beta-3d.jar//com.gmail.picono435.picojobs.libs.slimjar.app.builder.ApplicationBuilder.build(ApplicationBuilder.java:462)
[13:56:22 WARN]:        at PicoJobs-1.0-beta-3d.jar//com.gmail.picono435.picojobs.libs.slimjar.resolver.reader.facade.ReflectiveGsonFacadeFactory.create(ReflectiveGsonFacadeFactory.java:82)
[13:56:22 WARN]:        at PicoJobs-1.0-beta-3d.jar//com.gmail.picono435.picojobs.libs.slimjar.resolver.reader.facade.ReflectiveGsonFacadeFactory.create(ReflectiveGsonFacadeFactory.java:72)
[13:56:22 WARN]:        at PicoJobs-1.0-beta-3d.jar//com.gmail.picono435.picojobs.libs.slimjar.app.builder.ApplicationBuilder.getDataProviderFactory(ApplicationBuilder.java:351)
[13:56:22 WARN]:        at PicoJobs-1.0-beta-3d.jar//com.gmail.picono435.picojobs.libs.slimjar.app.builder.InjectingApplicationBuilder.buildApplication(InjectingApplicationBuilder.java:56)
[13:56:22 WARN]:        at PicoJobs-1.0-beta-3d.jar//com.gmail.picono435.picojobs.libs.slimjar.app.builder.ApplicationBuilder.build(ApplicationBuilder.java:462)
[13:56:22 WARN]:        at PicoJobs-1.0-beta-3d.jar//com.gmail.picono435.picojobs.PicoJobsPlugin.onLoad(PicoJobsPlugin.java:100)
[13:56:22 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:425)
[13:56:22 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:322)
[13:56:22 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1230)
[13:56:22 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[13:56:22 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)

**To Reproduce**
1. I get you Plugin on the Plugin folder and rann them (Error so I configure them)
2. After that I go to the Config and configure all. Change the Language to de-DE
3. Restart the Server
4. Server startet = Error happend

**Software Details:**
 - Server Software: Minecraft Pupur an Fork of Paper under Waterfall
 - Server Software Version: Pupur Version 1423; Waterfall Version 452 all on 1.17.1
 - Plugin Version 1.0-beta-3d
 - Java Version: Java 16

**Additional context**
Thanks to fix that and to read my error.
Have a nice Day!

**Comment by Picono435** [comment] 2021-11-05 14:50
This is a known issue and a temporary fix is being implemented while we wait for SLIMJAR to fix the issue.

**Comment by editon96** [comment] 2021-11-05 15:13
**Also nown?**
[15:51:13 FATAL]: Uncaught exception in thread Profile Lookup Executor #1
java.util.ConcurrentModificationException: null
        at com.google.common.collect.LinkedHashMultimap$ValueSet$1.checkForComodification(LinkedHashMultimap.java:376) ~[patched_1.17.1.jar:git-Purpur-1423]
        at com.google.common.collect.LinkedHashMultimap$ValueSet$1.hasNext(LinkedHashMultimap.java:382) ~[patched_1.17.1.jar:git-Purpur-1423]
        at java.util.AbstractCollection.toString(Unknown Source) ~[?:?]
        at java.lang.String.valueOf(Unknown Source) ~[?:?]
        at java.lang.StringBuilder.append(Unknown Source) ~[?:?]
        at java.util.AbstractMap.toString(Unknown Source) ~[?:?]
        at com.google.common.collect.AbstractMapBasedMultimap$AsMap.toString(AbstractMapBasedMultimap.java:1357) ~[patched_1.17.1.jar:git-Purpur-1423]
        at com.google.common.collect.AbstractMultimap.toString(AbstractMultimap.java:263) ~[patched_1.17.1.jar:git-Purpur-1423]
        at com.google.common.collect.LinkedHashMultimap.toString(LinkedHashMultimap.java:80) ~[patched_1.17.1.jar:git-Purpur-1423]
        at com.google.common.collect.ForwardingObject.toString(ForwardingObject.java:63) ~[patched_1.17.1.jar:git-Purpur-1423]
        at java.lang.String.valueOf(Unknown Source) ~[?:?]
        at java.lang.StringBuffer.append(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.libs.org.apache.commons.lang3.builder.ToStringStyle.appendDetail(ToStringStyle.java:626) ~[patched_1.17.1.jar:git-Purpur-1423]
        at org.bukkit.craftbukkit.libs.org.apache.commons.lang3.builder.ToStringStyle.appendInternal(ToStringStyle.java:590) ~[patched_1.17.1.jar:git-Purpur-1423]
        at org.bukkit.craftbukkit.libs.org.apache.commons.lang3.builder.ToStringStyle.append(ToStringStyle.java:476) ~[patched_1.17.1.jar:git-Purpur-1423]
        at org.bukkit.craftbukkit.libs.org.apache.commons.lang3.builder.ToStringBuilder.append(ToStringBuilder.java:846) ~[patched_1.17.1.jar:git-Purpur-1423]
        at com.mojang.authlib.GameProfile.toString(GameProfile.java:108) ~[patched_1.17.1.jar:git-Purpur-1423]
        at java.lang.String.valueOf(Unknown Source) ~[?:?]
        at java.lang.StringBuilder.append(Unknown Source) ~[?:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:202) ~[patched_1.17.1.jar:git-Purpur-1423]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38) ~[patched_1.17.1.jar:git-Purpur-1423]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:186) ~[patched_1.17.1.jar:git-Purpur-1423]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31) ~[patched_1.17.1.jar:git-Purpur-1423]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$2(SkullBlockEntity.java:157) ~[app:?]
        at net.minecraft.Util.ifElse(Util.java:397) ~[app:?]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$5(SkullBlockEntity.java:154) ~[app:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
[15:51:26 INFO]: editon96 issued server command: /jobsadmin
[15:52:06 INFO]: editon96 issued server command: /jobsadmin editor
[15:52:06 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'jobsadmin' in plugin PicoJobs v1.0-beta-3d
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Purpur-1423]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Purpur-1423]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Purpur-1423]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2344) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2155) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2136) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1423]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1447) ~[patched_1.17.1.jar:git-Purpur-1423]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-1423]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1425) ~[patched_1.17.1.jar:git-Purpur-1423]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Purpur-1423]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Purpur-1423]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1307) ~[patched_1.17.1.jar:git-Purpur-1423]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1423]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: com/gmail/picono435/picojobs/libs/jackson/core/JsonFactory
        at com.gmail.picono435.picojobs.commands.JobsAdminCommand.createEditor(JobsAdminCommand.java:292) ~[PicoJobs-1.0-beta-3d.jar:?]
        at com.gmail.picono435.picojobs.commands.JobsAdminCommand.onCommand(JobsAdminCommand.java:204) ~[PicoJobs-1.0-beta-3d.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Purpur-1423]
        ... 21 more
Caused by: java.lang.ClassNotFoundException: com.gmail.picono435.picojobs.libs.jackson.core.JsonFactory
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patched_1.17.1.jar:git-Purpur-1423]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[patched_1.17.1.jar:git-Purpur-1423]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at com.gmail.picono435.picojobs.commands.JobsAdminCommand.createEditor(JobsAdminCommand.java:292) ~[PicoJobs-1.0-beta-3d.jar:?]
        at com.gmail.picono435.picojobs.commands.JobsAdminCommand.onCommand(JobsAdminCommand.java:204) ~[PicoJobs-1.0-beta-3d.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Purpur-1423]
        ... 21 more

**Comment by Picono435** [comment] 2021-11-05 15:30
Yes but no... PicoJobs editor is still not released on the web...this issue happens because the plugin is set with the wrong web server, so instead sending a message saying it is still in development it throws an error. 

Going to fix that asap.

**Comment by Picono435** [comment] 2021-11-11 23:26
This issue should be fixed in the latest dev build (https://github.com/Picono435/PicoJobs/actions/runs/1450921169) In order to download it go to the link and scroll down to Builds, then just extract the zip. Also make sure to delete your libraries folder inside the PicoJobs directory.

This issue will be closed once I have the confirmation of the fix.

**Comment by Picono435** [comment] 2021-11-12 19:04
I got the confirmation that the issue is indeed fixed, you can update to 1,0-beta-4 and it should not happen again.

If this issue persists somehow make sure to re-open this issue or just create another one.

**Closed as completed by Picono435** 2021-11-12 19:04 UTC
Labels: bug
